server.port=8080
spring.application.name=student-api-spring

# Swagger & OpenAPI Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
