global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000', 'host.docker.internal:3000', 'localhost:3000']
        labels:
          app: 'campusconnect'
          service: 'api-gateway'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
