apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: lab8
  labels:
    app: api-gateway
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
      name: http
  selector:
    app: api-gateway
