apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: lab8
  labels:
    app: order-service
    service: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        service: backend
    spec:
      containers:
        - name: order-service
          image: order-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
              name: http
          envFrom:
            - configMapRef:
                name: campusconnect-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /orders
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /orders
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 15
